# Generated by Django 6.0 on 2025-12-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='mind_map_data',
            field=models.JSONField(blank=True, help_text='Saved mind map nodes and edges', null=True),
        ),
    ]
